version: '3.2'

services:
  message-broker:
    image: rabbitmq:3-management
    container_name: email-shooter-broker
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - email-shooter-net

  producer:
    build: 
      context: ./AppProducer
    container_name: email-shooter-producer
    networks:
      - email-shooter-net
    environment:
      - MESSAGE_BROKER_QUEUE_DEFAULT=EMAIL_QUEUE
      - MESSAGE_BROKER_URL=amqp://guest:guest@message-broker:5672/
    depends_on:
      - message-broker

networks:
  email-shooter-net:
    driver: bridge
    